### PR TITLE
Add if-else statement to change_read() in main.py to print a confirma…

### PR DESCRIPTION
**Pull request by laneenget**
@azhdrake Please look over this confirmation message

### CODE REVIEW

**Comment by azhdrake** [comment]
Looks good, although I think on lines 68 and 70 we should be using the ui.message() function rather then using print() directly, to better separate the UI from the back end.

**Comment by laneenget** [comment]
Good point. I will change that.

**Comment by azhdrake** [comment]
Found a bug. Message given after changing a book status is "you have not read..." regardless of if status was set to read or not read.

**Comment by laneenget** [comment]
It looks like ui.get_read_value() on line 59 always returns read regardless of what the user inputs.  I am not sure why, but maybe I am just misinterpreting the code.

Also, I realized ui.message() isn't working for the change_read() function. Are you having that problem too?

**Comment by laneenget** [comment]
You obviously are not having that problem if you're getting the "not read" message. I am at a loss then. I'll keep looking.

**Comment by azhdrake** [comment]
I had to make some executive decisions when I merged your branch with my more updated code.  My change_read() function looks like this now, which I think should be the same as yours?

`
def change_read():
    book_id = ui.get_book_id()
    book = store.get_book_by_id(book_id)
    new_read = ui.get_read_value()     
    book.read = new_read 

    if book.read == 'read':
        ui.message(f'You have read {book.title} by {book.author}.')
    else:
        ui.message(f'You have not read {book.title} by {book.author}.')

    book.save()`

**Comment by laneenget** [comment]
I saw there were some conflicts with master, but I haven't pulled master since pushing my branches to github. I don't know how or why but for some reason the message was not showing up until I left the branch and returned, so at least that issue is fixed for me. I still am not sure why only the 'not read' message is showing up, but I will keep looking.

**Comment by azhdrake** [comment]
book.read is a boolean, not a string. It will never equal read, only true/false

**Comment by laneenget** [comment]
That's what I thought but why does it say it returns 'read'

**Comment by azhdrake** [comment]
You mean in the constructor? notice that it's not a string. It's saying "self.read, aka the read that I'm keeping track of, is equal to the read value I've jest been feed by the method call". It's not saying self.read = the value "read"

**Comment by laneenget** [comment]
Fixed it

**Pull request merged**
